language: python
python:
  - 3.7
install: pip install -r requirements.txt
# before_script:
#   - export APP_CONFIG_FILE=development
#   - export FLASK_APP="nisse"
#   - export FLASK_DEBUG=1

# script: python -m unittest

jobs:
  include:
    - stage: test
      before_script:
        - export APP_CONFIG_FILE=development
        - export FLASK_APP="nisse"
        - export FLASK_DEBUG=1
      script: 
        - python -m unittest

    - stage: image    
      services:
        - docker
      before_script:
        - cd misc
        - openssl aes-256-cbc -K $encrypted_67daa94222db_key -iv $encrypted_67daa94222db_iv -in deploy_config.tar.gz.enc -out deploy_config.tar.gz -d
        - ls -al 
        - docker login registry.nexo.zone -u gitlab-ci -p $ci_token
        - export `cat __version__.py | sed 's/ //g' | sed 's/"//g'`
        - docker build -t registry.nexo.zone/internal/nisse-ci:`echo $__version__`.dev .
        - docker push registry.nexo.zone/internal/nisse-ci:`echo $__version__`.dev
      script: 
        - echo "test"
