"""empty message

Revision ID: 03487f0e792e
Revises: 0fdb6edfbd1b
Create Date: 2019-12-13 10:32:09.097175

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03487f0e792e'
down_revision = '0fdb6edfbd1b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('food_order', 'order_date',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('food_order_item', 'cost',
               existing_type=sa.NUMERIC(precision=18, scale=2),
               nullable=False)
    op.alter_column('food_order_item', 'paid',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('food_order_item', 'surrender',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('food_order_item', 'surrender',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('food_order_item', 'paid',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('food_order_item', 'cost',
               existing_type=sa.NUMERIC(precision=18, scale=2),
               nullable=True)
    op.alter_column('food_order', 'order_date',
               existing_type=sa.DATE(),
               nullable=True)
    # ### end Alembic commands ###
