"""empty message

Revision ID: 0fdb6edfbd1b
Revises: e86c2eef044c
Create Date: 2019-12-12 19:10:05.770325

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0fdb6edfbd1b'
down_revision = 'e86c2eef044c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('food_order', sa.Column('reminder', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('food_order', 'reminder')
    # ### end Alembic commands ###
