"""add_remid_time_columns

Revision ID: 382223577313
Revises: 5d0319bc37f6
Create Date: 2018-07-02 10:22:50.466804

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '382223577313'
down_revision = '5d0319bc37f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.add_column('users', sa.Column('remind_time_monday', sa.Time(), nullable=True))
    op.add_column('users', sa.Column('remind_time_tuesday', sa.Time(), nullable=True))
    op.add_column('users', sa.Column('remind_time_wednesday', sa.Time(), nullable=True))
    op.add_column('users', sa.Column('remind_time_thursday', sa.Time(), nullable=True))
    op.add_column('users', sa.Column('remind_time_friday', sa.Time(), nullable=True))
    op.add_column('users', sa.Column('remind_time_saturday', sa.Time(), nullable=True))
    op.add_column('users', sa.Column('remind_time_sunday', sa.Time(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'remind_time_wednesday')
    op.drop_column('users', 'remind_time_tuesday')
    op.drop_column('users', 'remind_time_thursday')
    op.drop_column('users', 'remind_time_sunday')
    op.drop_column('users', 'remind_time_saturday')
    op.drop_column('users', 'remind_time_monday')
    op.drop_column('users', 'remind_time_friday')
    # ### end Alembic commands ###
