"""adjusted_token_table

Revision ID: 5c77f4799359
Revises: cbb870be3cbc
Create Date: 2018-12-19 12:38:19.802492

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c77f4799359'
down_revision = 'cbb870be3cbc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tokens', sa.Column('scopes', sa.String(length=4096), nullable=True))
    op.add_column('tokens', sa.Column('token', sa.String(length=255), nullable=True))
    op.add_column('tokens', sa.Column('token_uri', sa.String(length=255), nullable=True))
    op.drop_constraint('tokens_access_token_key', 'tokens', type_='unique')
    op.create_unique_constraint('tokens_token_key', 'tokens', ['token'])
    op.drop_column('tokens', 'access_token')
    op.drop_column('tokens', 'token_type')
    op.alter_column('tokens', 'client_id', existing_type=sa.VARCHAR(40), type_=sa.VARCHAR(length=255), nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tokens', sa.Column('token_type', sa.VARCHAR(length=40), autoincrement=False, nullable=True))
    op.add_column('tokens', sa.Column('access_token', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_constraint('tokens_token_key', 'tokens', type_='unique')
    op.create_unique_constraint('tokens_access_token_key', 'tokens', ['access_token'])
    op.drop_column('tokens', 'token_uri')
    op.drop_column('tokens', 'token')
    op.drop_column('tokens', 'scopes')
    op.alter_column('tokens', 'client_id', existing_type=sa.VARCHAR(255), type_=sa.VARCHAR(length=40), nullable=False)
    # ### end Alembic commands ###
