"""add_phone_number

Revision ID: 7dcb49b666a6
Revises: 03487f0e792e
Create Date: 2019-12-13 11:13:04.254404

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import orm
from nisse.models.database import User
from slackclient import SlackClient
from flask import Flask
from nisse.utils.configs import load_config

# revision identifiers, used by Alembic.
revision = '7dcb49b666a6'
down_revision = '03487f0e792e'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('phone', sa.String(length=15), nullable=True))

    application = Flask(__name__, instance_relative_config=True)
    load_config(application)

    slack_client = SlackClient(application.config['SLACK_BOT_ACCESS_TOKEN'])

    slack_user_list = slack_client.api_call(
        "users.list"
    )

    phones = dict()
    for s in slack_user_list['members']:
        if 'profile' in s and 'email' in s['profile']:
            phones[s['profile']['email']] = s['profile']['phone']

    bind = op.get_bind()
    session = orm.Session(bind=bind)

    for user in session.query(User):
        if user.username in phones:
            user.phone = phones[user.username]

    session.commit()
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'phone')
    # ### end Alembic commands ###
