"""add_food_model

Revision ID: 8e40e31eff4d
Revises: 3bb17e0138f8
Create Date: 2019-12-12 14:03:43.353943

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '8e40e31eff4d'
down_revision = '3bb17e0138f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('food_order',
    sa.Column('food_order_id', sa.Integer(), nullable=False),
    sa.Column('order_date', sa.Date(), nullable=True),
    sa.Column('ordering_user_id', sa.Integer(), nullable=True),
    sa.Column('link', sa.String(length=512), nullable=True),
    sa.ForeignKeyConstraint(['ordering_user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('food_order_id')
    )
    op.create_table('food_order_item',
    sa.Column('food_order_item_id', sa.Integer(), nullable=False),
    sa.Column('food_order_id', sa.Integer(), nullable=True),
    sa.Column('eating_user_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('cost', sa.DECIMAL(precision=18, scale=2), nullable=True),
    sa.Column('paid', sa.Boolean(), nullable=True),
    sa.Column('surrender', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['eating_user_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['food_order_id'], ['food_order.food_order_id'], ),
    sa.PrimaryKeyConstraint('food_order_item_id')
    )

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('food_order_item')
    op.drop_table('food_order')
    # ### end Alembic commands ###
